name: Renovate Config

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
  workflow_dispatch:

jobs:
  prettier-format-check:
    name: Format Check
    uses: bymbly/gha-workflows/.github/workflows/prettier-format-check.yaml@main

  markdown-lint-check:
    name: Lint Check
    uses: bymbly/gha-workflows/.github/workflows/markdown-lint-check.yaml@main
